issuer: https://dex.sighup.io
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
telemetry:
  http: 0.0.0.0:5558
connectors:
- type: ldap
  id: ldap
  name: LDAP
  config:
    host: ldap.sighup.net:389
    insecureNoSSL: true
    bindDN: CN=ldap,CN=Users,DC=ad,DC=sighup,DC=io
    bindPW: xxxxxxxxx
    userSearch:
      baseDN: DC=ad,DC=sighup,DC=io
      filter: "(objectClass=person)"
      username: sAMAccountName
      idAttr: DN
      emailAttr: mail
      nameAttr: displayName
    groupSearch:
      baseDN: DC=ad,DC=easywelfare,DC=net
      filter: "(objectClass=group)"
      # A user is a member of a group when their DN matches
      # the value of a "member" attribute on the group entity.
      userAttr: DN
      groupAttr: member
      # The group name should be the "cn" value.
      nameAttr: cn
oauth2:
  skipApprovalScreen: true
staticClients:
- id: example-client-id # this is the oidc-client-id paramether in kube-apiserver configuration
  redirectURIs:
  - 'https://login-k8s.example.io/callback'
  name: 'Example Login'
  secret: example-client-id-secret
enablePasswordDB: false
