# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   annotations:
#     storageclass.kubernetes.io/is-default-class: "true"
#   name: vsphere
# provisioner: kubernetes.io/vsphere-volume
# parameters:
#   #datastore: DATASTORE
#   storagePolicyName: "POLICYNAME"
