
# configMapGenerator:
# - name: domain-chain-tls
#   namespace: kube-system
#   files:
#     - domain-chain.crt=resources/domain-chain.crt

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: domain-ssl
  namespace: kube-system
  type: kubernetes.io/tls
  files:
  - ca.crt=secrets/wildcard.domain.it.ca.crt
  - tls.crt=secrets/wildcard.domain.it.crt
  - tls.key=wsecrets/ildcard.domain.it.key


