---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: infra
spec:
  fluentbit:
    image:
      repository: registry.sighup.io/fury/fluent/fluent-bit
      tag: 1.9.5
  fluentd:
    image:
      repository: registry.sighup.io/fury/banzaicloud/fluentd
      tag: v1.14.6-alpine-5
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/infra
              operator: In
              values:
              - infra