apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: minio
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
