apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: minio
          volumeMounts:
            - name: data
              mountPath: /data      
          resources:
            limits:
              memory: 1000Mi
      volumes:
        - emptyDir:
            medium: Memory
          name: data
