# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: audit
spec:
  fileTailers:
    - name: audit
      containerOverrides:
        image: registry.sighup.io/fury/fluent/fluent-bit:1.6.1



