- name: Locally generate CA certificates for ETCD and MASTERS
  hosts: localhost
  tasks:
    - name: Generate etcd pkis
      delegate_to: localhost
      shell: "furyagent init etcd"
    - name: Generate master pkis
      delegate_to: localhost
      shell: "furyagent init master"
  tags:
    - pki-generate

- name: Copy PKI
  hosts: master
  vars:
    pki_dir: ../../secrets/printpdbc/pki
  tasks:
    - name: Create Etcd PKI directory
      file:
        path: /etc/etcd/pki/etcd
        owner: root
        group: root
        mode: 0750
        state: directory
    - name: Create Kubernetes PKI directory
      file:
        path: /etc/kubernetes/pki
        owner: root
        group: root
        mode: 0750
        state: directory
    - name: Copy Etcd CA
      copy:
        src: "{{ pki_dir }}/etcd/{{ item }}"
        dest: "/etc/etcd/pki/etcd/{{ item }}"
        owner: root
        group: root
        mode: 0640
      with_items:
        - ca.crt
        - ca.key
    - name: Copy Kubernetes CA
      copy:
        src: "{{ pki_dir }}/{{ item }}"
        dest: "/etc/kubernetes/pki/{{ item }}"
        owner: root
        group: root
        mode: 0640
      with_items:
        - ca.crt
        - ca.key
        - front-proxy-ca.crt
        - front-proxy-ca.key
        - sa.key
        - sa.pub
  tags:
    - pki-config

- name: Copy VMWare cloud config
  hosts: master
  vars:
    cloud_config: ../../secrets/printpdbc/vmware.conf
  tasks:
    - name: Create Kubernetes directory
      file:
        path: /etc/kubernetes
        owner: root
        group: root
        mode: 0750
        state: directory
    - name: Copy VMWare cloud config file
      copy:
        src: "{{ cloud_config }}"
        dest: "/etc/kubernetes/vmware.conf"
        owner: root
        group: root
        mode: 0640
  tags:
    - vmware-cloud-config

- name: Container enviroment preparation
  hosts: master,nodes
  roles:
    - on-premise/containerd
  tags:
    - container-node-common

- name: Kubernetes node preparation
  hosts: master,nodes
  roles:
    - on-premise/kube-node-common
  tags:
    - kube-node-common

- name: Etcd cluster preparation
  hosts: master
  roles:
    - on-premise/etcd
  tags:
    - etcd

- name: Control plane configuration
  hosts: master
  become: true
  vars:
    # kubernetes_pod_cidr: "172.31.0.0/16"
    # kubernetes_svc_cidr: "172.30.0.0/24"
    # kubernetes_cloud_provider: "vsphere"
    # kubernetes_cloud_config: "/etc/kubernetes/vmware.conf"
    kubernetes_cluster_name: "cluster-name"
    kubernetes_control_plane_address: "{{ control_plane_address }}"
    kubernetes_kubeconfig_path: "../secrets/users"
    kubernetes_users_org: "fineco-ops"
    kubernetes_users_names:
      - noops-nomecluster
    # oidc_issuer_url: "https://dex.nomecluster.domain.it"
    # oidc_client_id: "client-oidc"
    # oidc_ca_file: "/etc/pki/tls/cert.pem"
  roles:
    - on-premise/kube-control-plane
  tags:
    - kube-control-plane

- name: Kubernetes join nodes
  hosts: nodes
  become: true
  vars:
    kubernetes_control_plane_address: "{{ control_plane_address }}"
    kubernetes_bootstrap_token: "{{ hostvars[groups.master[0]].kubernetes_bootstrap_token.stdout }}"
    kubernetes_ca_hash: "{{ hostvars[groups.master[0]].kubernetes_ca_hash.stdout }}"
    # kubernetes_cloud_provider: "vsphere"
  roles:
    - on-premise/kube-worker
  tags:
    - kube-worker
