# ---

 - name: Reset etcd
   hosts: master
   tasks:
     - name: Remove etcd data dir
       file:
         path: /var/lib/etcd
         state: absent
     - name: Stop etcd
       service:
         name: etcd
         state: stopped
   tags:
     - reset-etcd

 - name: Reset Kubernetes cluster
   hosts: master,nodes
   tasks:
       - name: Reset kubeadm
         shell: "kubeadm reset -f"
       - name: Clean iptables
         shell: "iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
       - name: Clean IPVS
         shell: "ipvsadm --clear"
       - name: Stop etcd
         systemd:
             name: etcd
             state: stopped
         ignore_errors: yes
       - name: Clean etcd datadir
         file:
             path: /var/lib/etcd
             state: absent
         ignore_errors: yes
       - name: Cleanup pki etcd
         file:
             path: /etc/etcd/pki
             state: absent
         ignore_errors: yes
       - name: Cleanup pki kubernetes
         file:
             path: /etc/kubernetes/pki
             state: absent
         ignore_errors: yes
       - name: Reboot
         reboot:
   tags:
       - reset-kubernetes
