apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangway
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: gangway
        volumeMounts:
        - name: domain-chain
          mountPath: /tls/
      volumes:
      - name: domain-chain
        configMap:
          name: domain-chain-tls
