---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: kube-system
spec:
  template:
    spec:
      nodeSelector:
        node.kubernetes.io/role: infra
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/infra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangway
  namespace: kube-system
spec:
  template:
    spec:
      nodeSelector:
        node.kubernetes.io/role: infra
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/infra
