---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: ingress-nginx
spec:
  filters:
    - dedot:
        de_dot_separator: "_"
        de_dot_nested: true
    - parser:
        key_name: log
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: regexp
          expression: '/^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]+) \[(?<time_local>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*) +\S*)?" (?<status>\d+) (?<body_bytes_sent>\d+) "(?<http_referer>[^ ]*)" "(?<http_user_agent>[^\"]*)" (?<request_length>\d+) (?<request_time>[\d.]+) \[(?<proxy_upstream_name>[^\]]*)\] \[(?<proxy_alternative_upstream_name>[^\]]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>\d+|-) (?<upstream_response_time>[\d.]+|-) (?<upstream_status>\d+|-) (?<req_id>[^ ]*)/'
          time_key: time
          time_format: '%d/%b/%Y:%H:%M:%S %z'
  match:
    - select:
        labels:
          app: ingress
  localOutputRefs:
    - ingress-nginx